### ISSUE TITLE
ycm无法启动，出现The ycmd server SHUT DOWN

### ISSUE THREAD

**Issue by kim5659** [chxuan/vimplus#116]
硬件：树莓派3B
系统是centos7  32位最小安装版（1810）。
python3.6正常编译安装。
vim8用python3编译，vim --version显示+python3  -python.
使用的自动化安装ycm。
启动vim就会出现：The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). Unexpected exit code 1. Type ':YcmToggleLogs ycmd_33731_stderr_7wf7ekx6.log' to check the logs.
运行~/.vim/plugged/YouCompleteMe/install.sh后没用。
（我另一台设备（树莓派3B+），同样的系统，之前使用同样的安装方法的却可以正常使用）。
YcmToggleLogs ycmd_33731_stderr_7wf7ekx6.log内容如下：
Traceback (most recent call last):
  2   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
  3     "__main__", fname, loader, pkg_name)
  4   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
  5     exec code in run_globals
  6   File "/root/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/__main__.py", line 199, in <module>
  7     Main()
  8   File "/root/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/__main__.py", line 166, in Main
  9     code = ImportAndCheckCore()
 10   File "/root/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/utils.py", line 625, in ImportAndCheckCore
 11     LoadYcmCoreDependencies()
 12   File "/root/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/utils.py", line 610, in LoadYcmCoreDependenc
 13     ctypes.cdll.LoadLibrary( libclang_path )
 14   File "/usr/lib/python2.7/ctypes/__init__.py", line 438, in LoadLibrary
 15     return self._dlltype(name)
 16   File "/usr/lib/python2.7/ctypes/__init__.py", line 360, in __init__
 17     self._handle = _dlopen(self._name, mode)
 18 OSError: /lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/.vim/plugged/YouComplet
上面为什么会出现python2.7的东西？
centos系统里libstdc++.so.6只到`GLIBCXX_3.4.19，没有`GLIBCXX_3.4.20怎么办？
各位大神看看哪里出了问题，谢谢！

**Comment by chxuan** [comment]
@kim5659 ycm需要64位的系统支持

**Comment by kim5659** [comment]
> @kim5659 ycm需要64位的系统支持
我看了readme文件，我也知道ycm不是for32位系统，但你怎么解释，我另一个树莓派运行正常的问题。也是32位的系统。环境基本完全一样，只是无法运行的是树莓派3B，能正常运行的是树莓派3B+，只是cpu主频和有线网卡带宽不同而已，系统都一样。能解释吗？

**Comment by causlayer** [comment]
我的mac也出现了这个问题，ycm无法启动，出现The ycmd server SHUT DOWN，不过我的日志里错误是这个：
2019-03-24 02:30:32,199 - ERROR - HTTPConnectionPool(host='127.0.0.1', port=60990): Max retries exceeded with url: /ready (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10e50a4e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2019-03-24 02:30:32,299 - ERROR - The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). Unexpected exit code 0. Type ':YcmToggleLogs ycmd_60990_stderr_pqs0r4g1.log' to check the logs.
我打开ycmd_60990_stderr_pqs0r4g1.log里面是空。
@chxuan
